Update pathways server and proxy server image locations
google/xpk pull request #143
Opened 2024-05-03 22:08 UTC by sadikneipp

Our images have been migrated to Artifact registry. This is the current source of truth for good pathways images.

2024-05-03 22:16 UTC, RoshaniN commented
Thanks for the change, Sadi!
Please fix lint with "pyink ."

2024-05-03 22:16 UTC, RoshaniN requested changes
Thanks for the change, Sadi!
Please fix lint with "pyink ."

2024-05-07 20:51 UTC, RoshaniN approved these changes

2024-05-08 17:02 UTC, Obliviour approved these changes

2024-05-08 21:20 UTC, merged